#!/bin/bash
#
# Startup script for Cheops-NG agent.
#
# Maxim Heijndijk <cchq@wanadoo.nl>
#
# chkconfig: 2345 90 15
# description: Multipurpose network exploration tool.
# processname: cheops-agent
# config: /etc/sysconfig/cheops-agent

# Source function library.
. /etc/init.d/functions

# See how we were called.
case "$1" in

        start)	gprintf "Starting Cheops-NG Agent: "
		daemon cheops-agent -n &
		touch /var/lock/subsys/cheops-agent
		echo
		;;

        stop)	gprintf "Stopping  Cheops-NG Agent: "
    		killproc cheops-agent
		rm -fr /var/lock/subsys/cheops-agent
		echo
                ;;

        restart|reload)	$0 stop
        		$0 start
			;;

        status)	status cheops-agent
		;;

	*)	gprintf "Usage: cheops-agent {start|stop|restart|reload|status}\n"
		;;

esac

exit 0
